# Generated by Django 2.1.1 on 2018-10-07 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0002_project_modification_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='modification_time',
        ),
    ]
